name = "schwimmen"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "SCHWIMMEN_KV"
id = "ff02a4f607d34602bb655e513a65f6e3"

[[durable_objects.bindings]]
name = "GAME_ROOMS"
class_name = "GameRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]
